apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: sampleapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: teopocregistery.azurecr.io/spring-boot-docker-example:0.0.1-SNAPSHOT
        env:
        ports:
          - name: http-port
            containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 3G
          requests:
            cpu : 10m
            memory: 350M
