apiVersion: v1
kind: Service
metadata:
  name: sampleapp-svc
  namespace: sampleapplication
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080  
  selector:
    app: sampleapp
